### ISSUE TITLE
[BUG] oca_sing: There is no confirmation upon signing the document

### ISSUE THREAD

**Issue by antoniospneto** [OCA/sign#23]
## Module
oca_sign

## Describe the bug
When the signing user clicks on "Validate & Send Document," no information or action is displayed to the user; no confirmation screen of submission is shown, and the validate button continues to be displayed as if nothing has happened.
![image](https://github.com/OCA/sign/assets/634278/98c68864-815f-4330-810f-76158cb8acc6)

The user ends up thinking that the validation did not work and clicks the button again, then a notification is displayed stating that the document has already been signed:
![image](https://github.com/OCA/sign/assets/634278/fee2191c-9168-4131-84e4-62d119c30307)

## To Reproduce
**Affected versions**:
14.0

1. Create a new template.
2. Send it for signature.
3. Open the link to sign the document.
4. Fill in the information and click on "Validate & Send Document".

**Expected behavior**
Upon clicking the "Validate & Send Document" button, the user should be redirected to a page confirming the completion of the signed document, or a notification should be shown to the user.

**Additional context**
Upon reopening (F5) the document link after signing, this screen is displayed. I think it could be redirected to this screen after clicking the "Validate & Send Document" button.
![image](https://github.com/OCA/sign/assets/634278/c69735af-fa46-4384-8ca4-4f761dd7f69d)

Note: the email with the final document is not being sent by email after completion as I did in the message above, see:
![image](https://github.com/OCA/sign/assets/634278/10618c18-a2d7-491d-b46b-4a6814602a86)

**Comment by antoniospneto** [comment]
Looking at the code, it seems that this handling is indeed pending, there is a TODO marked for the creation of the return in the signature method:

https://github.com/OCA/sign/blob/8f555112c95ceae3d7a963c79575a6bca0220b24/sign_oca/models/sign_oca_request.py#L451

**Comment by marcelsavegnago** [comment]
ping @WesleyOliveira98
